### ISSUE TITLE
Update all versions of requirements to match gfe-db.

### ISSUE THREAD

**Issue by jbrelsf2-nmdp** [nmdp-bioinformatics/py-gfe#19]
Some requirements are out of date or have security flaws.  See security recommendations.

**Comment by abk7777** [comment]
This is true for the latest version of py-ard 0.6.1 which uses pandas >= 1.1.4, while py-gfe1.1.0 uses pandas 0.25.1.

**Comment by pbashyal-nmdp** [comment]
Fixed with #33
